version: '3'
services:
  mysql:
    image: mysql:8.0
    networks:
      - fc_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=pay
      - MYSQL_ROOT_PASSWORD=root1234!!
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=user
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  membership-service:
    image: my-pay-membership-service:0.0.1-SNAPSHOT
    networks:
      - fc_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234!!
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  fc_network:
    driver: bridge
